version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pgadmin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pochtaprint03@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


  tg:
    depends_on:
      - db
      - pgadmin
    container_name: Recept
    build: Recept/
    command:
      python Recept/tgbot.py && python Recept/menu_upd.py



