version: '2.1'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  pgadmin:
    depends_on:
      - db
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pochtaprint03@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"




  tg:
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    container_name: Recept
    build: Recept/
    command:
      bash Recept/run.sh


